init:
# Uncomment to get the rdp login for the build agent
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input
  - git config --global push.default simple
  
version: 1.0.{build}
environment:
  secret-github-user: test

  secret-github-password: testpass

  secret-nuget-api: testkey

build_script:
- cmd: "build.cmd Build"

deploy:
- provider: Local
  on:
    branch: master

before_deploy:
- cmd: >-
    @ECHO OFF
    
    SETX -m NugetKey %secret-nuget-api%
    
    SETX -m github-user %secret-github-user%
    
    SETX -m github-pw %secret-github-password%
after_deploy:
- ps: >-
    $p = Start-Process -FilePath "./build.cmd" -ArgumentList "Release" -Wait -PassThru
    
    $p.ExitCode
    
# uncomment to debug will stop the build server for 1 hour
#on_finish:
#- cmd: pause
