init:
# Uncomment to get the rdp login for the build agent
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input
  - git config --global push.default simple
version: 1.0.{build}
environment:
  secret-github-user:
    secure: z3TsP5/PRDg4wIedgeRAtR8edLoACEuSmbToUTXzcf4=

  secret-github-password:
    secure: Fu6p8pFA2CEmOLfszUJf3ayF3dL9DsorBluoiQKJUNkpCcAlxlubScpvGDgxFAyH

  secret-nuget-api:
    secure: ANJVg76+ZG8oux3kZiS8MazTByIDILozxNJfQGa0zD3+1+jXaPN152mDu4JFyuka

build_script:
- cmd: "build.cmd Build"

deploy:
- provider: Local
  on:
    branch: master

before_deploy:
- cmd: >-
    setx NugetKey = %secret-nuget-api%

    setx github-user = %secret-github-user%

    setx github-password = %secret-github-password%

after_deploy:
- ps: >-
    Start-Process -FilePath ./build.cmd -ArgumentList Release -Wait -NoNewWindow 
# uncomment to debug will stop the build server for 1 hour
# on_finish:
# - ps: $blockRdp = $true;
